### ISSUE TITLE
Interval() takes no arguments

### ISSUE THREAD

**Issue by arshidkv12** [sabuhish/fastapi-mail#206]
Python Version: 3.9.7
venv activated
fastapi_mail : 1.4.1

```
Traceback (most recent call last):
  File "/Users/arshid/Desktop/test/fast-mail-test/ma-test.py", line 2, in <module>
    from fastapi_mail import FastMail, MessageSchema, ConnectionConfig
  File "/Users/arshid/Desktop/test/fast-mail-test/venv/lib/python3.9/site-packages/fastapi_mail/__init__.py", line 1, in <module>
    from fastapi_mail.config import ConnectionConfig
  File "/Users/arshid/Desktop/test/fast-mail-test/venv/lib/python3.9/site-packages/fastapi_mail/config.py", line 9, in <module>
    class ConnectionConfig(Settings):
  File "/Users/arshid/Desktop/test/fast-mail-test/venv/lib/python3.9/site-packages/fastapi_mail/config.py", line 16, in ConnectionConfig
    MAIL_DEBUG: conint(gt=-1, lt=2) = 0  # type: ignore
  File "/Users/arshid/Desktop/test/fast-mail-test/venv/lib/python3.9/site-packages/pydantic/types.py", line 225, in conint
    annotated_types.Interval(gt=gt, ge=ge, lt=lt, le=le),
TypeError: Interval() takes no arguments
```

**Comment by sabuhish** [comment]
I tested it on Python 3.11.9, no issue occurs. Maybe check your pydantic version.
