### ISSUE TITLE
how to set up anonymous sender?

### ISSUE THREAD

**Issue by rockonedege** [sabuhish/fastapi-mail#47]
I was configuring fast-api against an exchange server that allows anonymous user to send email.

with `flask-mail`, I could achieve it by NOT setting it at all, i.e. comment it out
```python
# app.config['MAIL_USERNAME']
# app.config['MAIL_PASSWORD']
```
with 'fast-api', doing the same resulting in
```
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from routers import mail as mail_api
  File "mail.py", line 36, in <module>
    conf = ConnectionConfig(
  File "lib\site-packages\pydantic\env_settings.py", line 34, in __init__
    super().__init__(
  File "lib\site-packages\pydantic\main.py", line 362, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 2 validation errors for ConnectionConfig
MAIL_USERNAME
  field required (type=value_error.missing)
MAIL_PASSWORD
  field required (type=value_error.missing)
```

setting them to `None` yields another error
```
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from routers import mail as mail_api
  File "mail.py", line 36, in <module>
    conf = ConnectionConfig(
  File "lib\site-packages\pydantic\env_settings.py", line 34, in __init__
    super().__init__(
  File "lib\site-packages\pydantic\main.py", line 362, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 3 validation errors for ConnectionConfig
MAIL_USERNAME
  none is not an allowed value (type=type_error.none.not_allowed)
MAIL_PASSWORD
  none is not an allowed value (type=type_error.none.not_allowed)
```

I did not try setting them to empty string, as when I did that to `flask-mail`, it failed to pass the authentication.

Does fast-api support this anonymous scenario? if so, what the correct setting?

**Comment by sabuhish** [comment]
Currently, there is no support for this feature. We are working on this, we will see if we can make this work.
