### ISSUE TITLE
SMTPServerDisconnected

### ISSUE THREAD

**Issue by mattiacampana** [sabuhish/fastapi-mail#54]
I'm having trouble sending emails from my web service hosted on Digital Ocean, while everything works fine from my local machine.

The full traceback is the following:

```
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
File "/usr/lib/python3/dist-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
File "/home/mattia/.local/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
     await super().__call__(scope, receive, send)
File "/home/mattia/.local/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
     await self.middleware_stack(scope, receive, send)
File "/home/mattia/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
     raise exc from None
File "/home/mattia/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
     await self.app(scope, receive, _send)
File "/home/mattia/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
     raise exc from None
File "/home/mattia/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
     await self.app(scope, receive, sender)
File "/home/mattia/.local/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
     await route.handle(scope, receive, send)
File "/home/mattia/.local/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
     await self.app(scope, receive, send)
File "/home/mattia/.local/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
     response = await func(request)
File "/home/mattia/.local/lib/python3.8/site-packages/fastapi/routing.py", line 201, in app
     raw_response = await run_endpoint_function(
File "/home/mattia/.local/lib/python3.8/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
     return await dependant.call(**values)
File "./app/routers/users.py", line 98, in send_validation_email
     await fm.send_message(message)
File "/home/mattia/.local/lib/python3.8/site-packages/fastapi_mail/fastmail.py", line 92, in send_message
     email_dispatched.send(msg)
File "/home/mattia/.local/lib/python3.8/site-packages/fastapi_mail/connection.py", line 30, in __aexit__
     await self.session.quit()
File "/home/mattia/.local/lib/python3.8/site-packages/aiosmtplib/esmtp.py", line 236, in quit
     response = await self.execute_command(b"QUIT", timeout=timeout)
File "/home/mattia/.local/lib/python3.8/site-packages/aiosmtplib/connection.py", line 420, in execute_command
     response = await self.protocol.execute_command(*args, timeout=timeout)
File "/home/mattia/.local/lib/python3.8/site-packages/aiosmtplib/protocol.py", line 290, in execute_command
     self.write(command)
File "/home/mattia/.local/lib/python3.8/site-packages/aiosmtplib/protocol.py", line 274, in write
     raise SMTPServerDisconnected("Connection lost")
aiosmtplib.errors.SMTPServerDisconnected: Connection lost
```

and this is my code:

```python
@router.post("/users/send_validation_email/{email}", tags=["users"],
            responses={
                400: {"description": "The user's email has been already verified"},
                404: {"description": "User not found"}
            }
)
async def send_validation_email(email: str, lang: str, background_tasks: BackgroundTasks):

    user = users_crud.get_user_by_email(email=email)

    if user is None:
        raise HTTPException(status_code=404, detail="User not found")
    elif user is not None and user["email_verified"] is True:
        raise HTTPException(status_code=400, detail="The user's email has been already verified")

    message = email_utils.get_validation_mail(user_id=str(user["_id"]), email_address=user["email"], user_name=user['first_name'], lang=lang)

    if message is not None:
        fm = FastMail(conf)
        #background_tasks.add_task(fm.send_message, message)
        await fm.send_message(message)

    return JSONResponse(status_code=200, content={"message": "email has been sent"})
```

I tried using both `BackgroundTasks` and `await` but the result is the same: on my local machine it sends the email and on the DigitalOcean virtual server doesn't. Do you have any suggestions?

**Comment by sabuhish** [comment]
Interesting behavior, can I see your configuration with hiding your credentials. Error raised on opening connection, on the server session is not established. I hope you don't set SUPPRESS_SEND=1. Let me see, we will try to figure it out.

**Comment by sabuhish** [comment]
Could you fix this issue? this problem might occur because of the DigitalOcean. Can you try other service providers to see if problem occurs because of digital ocean or not?

**Comment by sabuhish** [comment]
Guessing you have solved this issue, closing this if you have other issues feel free to open new one.
