### ISSUE TITLE
Issue with running the demo code

### ISSUE THREAD

**Issue by ZhengRui** [sabuhish/fastapi-mail#65]
Hi, thanks for the nice work! I am trying out the demo code to send an email from my gmail to other email address, but having this issue right now, any ideas what could be the reason? Thanks. 

```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/fastapi/applications.py", line 190, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 189, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 135, in run_endpoint_function
    return await dependant.call(**values)
  File "./app.py", line 53, in simple_send
    await fm.send_message(message)
  File "/usr/local/lib/python3.7/site-packages/fastapi_mail/fastmail.py", line 88, in send_message
    await session.session.send_message(msg)
  File "/usr/local/lib/python3.7/site-packages/aiosmtplib/smtp.py", line 299, in send_message
    timeout=timeout,
  File "/usr/local/lib/python3.7/site-packages/aiosmtplib/smtp.py", line 179, in sendmail
    raise exc
  File "/usr/local/lib/python3.7/site-packages/aiosmtplib/smtp.py", line 165, in sendmail
    timeout=timeout,
  File "/usr/local/lib/python3.7/site-packages/aiosmtplib/esmtp.py", line 271, in mail
    raise SMTPSenderRefused(response.code, response.message, sender)
aiosmtplib.errors.SMTPSenderRefused: (530, '5.7.0 Authentication Required. Learn more at\n5.7.0  https://support.google.com/mail/?p=WantAuthError mq12sm156656pjb.23 - gsmtp', 'rui@zityspace.com')

```

**Comment by ZhengRui** [comment]
seems to be related to me using proxies , it works without using proxy, close the issue
